In [12]:
import pandas as pd
import numpy as np

from pandas import Series, DataFrame

# # 시리즈 객체
# list_data = [1,2,3,4,5]
# list_name = ["a", "b", "c", "d", "e"]
# example_obj = Series(data = list_data, index = list_name)
# print(example_obj)
# print(example_obj.index)
# print(example_obj.values)
# print(type(example_obj.values))
# print(example_obj.dtype)
# # 시리즈 객체의 이름 변경, 지정
# example_obj.name = "number"
# example_obj.index.name = "id"
# print(example_obj)

# # 시리즈 객체의 생성
# dict_data = {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5} # 키는 인덱스, 값은 데이터
# example_obj = Series(dict_data, dtype=np.float32, name="example_data")
# print(example_obj)

# dict_data_1 = {"a":1, "b":2, "c":3, "d":4, "e":5}
# indexes = ["a","b","c","d","e","f","g","h"]
# series_obj_1 = Series(dict_data_1, index=indexes)
# print(series_obj_1)

# 데이터 프레임
# data_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data'
# # 데이터URL을변수data_url에 넣기
# df_data = pd.read_csv(data_url, sep='\s+', header = None) # csv 데이터로드
# df = pd.DataFrame(df_data)
# print(df)
# 데이터 프레임 직접 생성
# raw_data = {
#     'first_name': ['Jason', 'Molly', 'Tina', 'Jake', 'Amy'],
#     'last_name': ['Miller', 'Jacobson', 'Ali', 'Milner', 'Cooze'],
#     'age': [42, 52, 36, 24, 73],
#     'city': ['San Francisco', 'Baltimore', 'Miami', 'Douglas', 'Boston']
#     }
# df = pd.DataFrame(raw_data, columns = ['first_name',
#                                        'last_name',
#                                        'age',
#                                        'city'])
# print(df)
# df = pd.DataFrame(raw_data, columns = ['age',
#                                        'city'])
# print(df)
# df = pd.DataFrame(raw_data, columns = ['first_name',
#                                        'last_name',
#                                        'age',
#                                        'debt'])
# print(df)
# from google.colab import files
# uploaded = files.upload()

# import openpyxl
# df = pd.read_excel("excel-comp-data.xlsx")
# print(df)

# print('----------head')
# print(df.head(2))
# print('----------tail')
# print(df.tail(2))
# print(df[["account", "street", "state"]].head(3))
# print(df[:3])
# print(df[["name","street"]][:2])
# df.index = df["account"]
# del df["account"]
# print(df.head())
# df.index = df["account"]
# print(df.loc[[211829,320563],["name","street"]])

# df.index = df["account"]
# print(df.loc[205217:,["name","street"]] )

# print(df.iloc[:10, :3])

# df_new= df.reset_index()
# print(df_new.head())


# dr_drop = df_new.drop(1).head()
# print(dr_drop)

# df_new= df.reset_index()
# df_drop= df_new.drop(1)
# df_new.drop(1, inplace=True)
# df_new.drop("account", axis=1)  # account 열제거
# df_new.drop(["account", "name"], axis=1) # account, name 열제거

# 3-2 그룹별 집계
# ipl_data= {'Team': ['Riders', 'Riders', 'Devils', 'Devils', 'Kings','kings',
# 'Kings', 'Kings', 'Riders', 'Royals', 'Royals', 'Riders'],
#  'Rank': [1, 2, 2, 3, 3,4 ,1 ,1,2 , 4,1,2],
#  'Year': [2014, 2015, 2014, 2015, 2014, 2015, 2016, 2017, 2016, 2014,
# 2015, 2017],
#  'Points':[876,789,863,673,741,812,756,788,694,701,804,690]}

# df = pd.DataFrame(ipl_data)
# print(df)

# group_by = df.groupby("Team")["Points"].sum()
# print(group_by)

# multi_groupby = df.groupby(["Team", "Year"])["Points"].sum()
# print(multi_groupby)

# print(multi_groupby.index)
# print(multi_groupby["Devils":"Kings"])
# print(multi_groupby.unstack())
# print(multi_groupby.swaplevel().sort_index())
# multi_groupby.sum()
# print(multi_groupby.groupby(level=0).sum())
# print(multi_groupby.groupby(level=1).sum())

# grouped = df.groupby("Team")
# print(grouped.get_group("Riders"))
# print(grouped.agg(min))
# print(grouped.agg(np.mean))

# print(grouped.transform(max))
# score = lambda x: (x -x.mean()) / x.std()
# print(grouped.transform(score))

# filtered = df.groupby('Team').filter(lambda x: len(x) >= 3)
# print(filtered)
# filtered = df.groupby('Team').filter(lambda x: x["Points"].max() > 800)
# print(filtered)

# 병합
# raw_data_left= {
#  'subject_id': ['1', '2', '3', '4', '5', '7', '8', '9', '10', '11'],
#  'test_score': [51, 15, 15, 61, 16, 14, 15, 1, 61, 16]
#  }

# df_left= pd.DataFrame(raw_data_left, columns = ['subject_id', 'test_score'])

# raw_data_right= {
#   'subject_id': ['4', '5', '6', '7', '8'],
#   'first_name': ['Billy', 'Brian', 'Bran', 'Bryce', 'Betty'],
#   'last_name': ['Bonder', 'Black', 'Balwner', 'Brice', 'Btisan']
#   }

# df_right= pd.DataFrame(raw_data_right, columns = ['subject_id', 'first_name', 'last_name'])

# df_inner = pd.merge(left=df_left, right=df_right, how="inner", on='subject_id')
# print(df_inner)

# df_left = pd.merge(left=df_left, right=df_right, how="left", on='subject_id')
# print(df_left)

# df_right = pd.merge(left=df_left, right=df_right, how="right", on='subject_id')
# print(df_right)

# df_outer = pd.merge(df_left, df_right, on='subject_id', how='outer')
# print(df_outer)

# 연결
# from google.colab import files
# uploaded = files.upload()

import os
filenames = ['sales-feb.xlsx', 'sales-jan.xlsx', 'sales-mar.xlsx']
# print(filenames)

# df_list = [pd.read_excel(filename, engine="openpyxl") for filename in filenames]
# for df in df_list:
#   print(type(df), len(df))

# df = pd.concat(df_list, axis=0)
# print(len(df)) # 384
# print(df.reset_index(drop=True))

dfs = [pd.read_excel(filename, engine="openpyxl") for filename in filenames]
df = pd.concat(dfs, ignore_index=True)
print(df)

     account number                          name       sku  quantity  \
0            383080                      Will LLC  B1-20000         7
1            412290                 Jerde-Hilpert  S1-27722        11
2            412290                 Jerde-Hilpert  B1-86481         3
3            412290                 Jerde-Hilpert  B1-20000        23
4            672390               Kuhn-Gusikowski  S1-06532        48
..              ...                           ...       ...       ...
379          737550  Fritsch, Russel and Anderson  B1-65551        12
380          642753                   Pollich LLC  S1-93683        21
381          412290                 Jerde-Hilpert  B1-20000        30
382          307599   Kassulke, Ondricka and Metz  S2-16558        46
383          672390               Kuhn-Gusikowski  B1-04202        19

     unit price  ext price                 date
0         33.69     235.83  2014-02-01 09:04:59
1         21.12     232.32  2014-02-01 11:51:46
2         35.99     107.97  2014-02-01 17:24:32
3         78.90    1814.70  2014-02-01 19:56:48
4         55.82    2679.36  2014-02-02 03:45:20
..          ...        ...                  ...
379       56.24     674.88  2014-03-31 08:43:24
380       92.57    1943.97  2014-03-31 11:37:34
381       22.38     671.40  2014-03-31 21:41:31
382       56.04    2577.84  2014-03-31 22:11:22
383       27.86     529.34  2014-03-31 23:13:14

[384 rows x 7 columns]