In [53]:
import pandas as pd
import numpy as np

from pandas import Series, DataFrame

# # 시리즈 객체
# list_data = [1,2,3,4,5]
# list_name = ["a", "b", "c", "d", "e"]
# example_obj = Series(data = list_data, index = list_name)
# print(example_obj)
# print(example_obj.index)
# print(example_obj.values)
# print(type(example_obj.values))
# print(example_obj.dtype)
# # 시리즈 객체의 이름 변경, 지정
# example_obj.name = "number"
# example_obj.index.name = "id"
# print(example_obj)

# # 시리즈 객체의 생성
# dict_data = {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5} # 키는 인덱스, 값은 데이터
# example_obj = Series(dict_data, dtype=np.float32, name="example_data")
# print(example_obj)

# dict_data_1 = {"a":1, "b":2, "c":3, "d":4, "e":5}
# indexes = ["a","b","c","d","e","f","g","h"]
# series_obj_1 = Series(dict_data_1, index=indexes)
# print(series_obj_1)

# 데이터 프레임
# data_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data'
# # 데이터URL을변수data_url에 넣기
# df_data = pd.read_csv(data_url, sep='\s+', header = None) # csv 데이터로드
# df = pd.DataFrame(df_data)
# print(df)
# 데이터 프레임 직접 생성
# raw_data = {
#     'first_name': ['Jason', 'Molly', 'Tina', 'Jake', 'Amy'],
#     'last_name': ['Miller', 'Jacobson', 'Ali', 'Milner', 'Cooze'],
#     'age': [42, 52, 36, 24, 73],
#     'city': ['San Francisco', 'Baltimore', 'Miami', 'Douglas', 'Boston']
#     }
# df = pd.DataFrame(raw_data, columns = ['first_name',
#                                        'last_name',
#                                        'age',
#                                        'city'])
# print(df)
# df = pd.DataFrame(raw_data, columns = ['age',
#                                        'city'])
# print(df)
# df = pd.DataFrame(raw_data, columns = ['first_name',
#                                        'last_name',
#                                        'age',
#                                        'debt'])
# print(df)
# from google.colab import files
# uploaded = files.upload()

# import openpyxl
df = pd.read_excel("excel-comp-data.xlsx")
# print(df)

# print('----------head')
# print(df.head(2))
# print('----------tail')
# print(df.tail(2))
# print(df[["account", "street", "state"]].head(3))
# print(df[:3])
# print(df[["name","street"]][:2])
# df.index = df["account"]
# del df["account"]
# print(df.head())
# df.index = df["account"]
# print(df.loc[[211829,320563],["name","street"]])

# df.index = df["account"]
# print(df.loc[205217:,["name","street"]] )

# print(df.iloc[:10, :3])

# df_new= df.reset_index()
# print(df_new.head())


# dr_drop = df_new.drop(1).head()
# print(dr_drop)

# df_new= df.reset_index()
# df_drop= df_new.drop(1)
# df_new.drop(1, inplace=True)
# df_new.drop("account", axis=1)  # account 열제거
# df_new.drop(["account", "name"], axis=1) # account, name 열제거

,index,street,city,state,postal-code,Jan,Feb,Mar
0,0,34456 Sean Highway,New Jaycob,Texas,28752,10000,62000,35000
2,2,62184 Schamberger Underpass Apt. 231,New Lilianland,Iowa,76517,91000,120000,35000
3,3,155 Fadel Crescent Apt. 144,Hyattburgh,Maine,46021,45000,120000,10000
4,4,7274 Marissa Common,Shanahanchester,California,49681,162000,120000,35000
5,5,89403 Casimer Spring,Jeremieburgh,Arkansas,62785,150000,120000,35000
6,6,340 Consuela Bridge Apt. 400,Lake Gabriellaton,Mississipi,18008,62000,120000,70000
7,7,91971 Cronin Vista Suite 601,Deronville,RhodeIsland,53461,145000,95000,35000
8,8,26739 Grant Lock,Lake Juliannton,Pennsylvania,64415,70000,95000,35000
9,9,366 Maggio Grove Apt. 998,North Ras,Idaho,46308,70000,120000,35000
10,10,649 Cierra Forks Apt. 078,Rosaberg,Tenessee,47743,45000,120000,55000
11,11,18115 Olivine Throughway,Norbertomouth,NorthDakota,31415,150000,10000,162000
12,12,182 Bertie Road,East Davian,Iowa,72686,162000,120000,35000
13,13,2624 Beatty Parkways,Goodwinmouth,RhodeIsland,31919,55000,120000,35000
14,14,8917 Bergstrom Meadow,Kathryneborough,Delaware,27933,150000,120000,70000